[package]
name = "SonicSplit"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
jack = "0.13.0"
nalgebra = "0.33.2"
ringbuf = "0.4.7"
clap = { version = "4.5.20", features = ["derive"] }
